Repository BZFlag-Dev/bzflag.org, pull requests merged in 2019-02, with the labels that each got.

#5 added bad flag documentation
  _documentation/user/flags/blindness.md
  _documentation/user/flags/bouncy.md
  _documentation/user/flags/colorblindness.md
  _documentation/user/flags/forward-only.md
  _documentation/user/flags/jamming.md
  _documentation/user/flags/left-turn-only.md
  _documentation/user/flags/momentum.md
  _documentation/user/flags/no-jumping.md
  _documentation/user/flags/obesity.md
  _documentation/user/flags/reversecontrols.md
  _documentation/user/flags/reverseonly.md
  _documentation/user/flags/right-turn-only.md
  _documentation/user/flags/trigger-happy.md
  _documentation/user/flags/wide-angle.md
Labels: needs review

#7 Analysis of seer flag
  _documentation/user/flags/seer.md
Labels: granted ownership, needs review

#9 Analysis of ricochet flag
  _documentation/user/flags/ricochet.md
Labels: ready for merge

#11 Analysis of phantom zone flag
  _documentation/user/flags/phantom-zone.md
Labels: ready for merge

#12 Analysis of oscillation overthruster flag
  _documentation/user/flags/oscillation-overthruster.md
Labels: ready for merge

#10 Analysis of jumping flag
  _documentation/user/flags/jumping.md
Labels: ready for merge

#14 Add documentation for some API server functions
  _documentation/developer/bzfs_api_functions/bz_APIVersion.md
  _documentation/developer/bzfs_api_functions/bz_MD5.md
  _documentation/developer/bzfs_api_functions/bz_getProtocolVersion.md
  _documentation/developer/bzfs_api_functions/bz_getServerVersion.md
  _documentation/developer/bzfs_api_functions/bz_loadPlugin.md
  _documentation/developer/bzfs_api_functions/bz_unloadPlugin.md
Labels: ready for merge

#15 Analysis of identify flag
  _documentation/user/flags/identify.md
Labels: ready for merge

#17 Redesign "Getting Started" page to be less text heavy
  .gitignore
  _data/navigation.yaml
  _documentation/user/pages/getting_started.md
  _documentation/user/pages/index.md
  _macros/keyboard_utils.html.twig
  _macros/mouse_utils.html.twig
  _pages-partials/getting-started/01-register-callsign.html.twig
  _pages-partials/getting-started/02-tank-types.html.twig
  _pages-partials/getting-started/03-game-modes.html.twig
  _pages-partials/getting-started/04-super-flags.html.twig
  _pages-partials/getting-started/05-controls.html.twig
  _pages-partials/getting-started/06-user-interface.html.twig
  _pages/getting-started.html.twig
  _pages/help.html.twig
  _pages/index.html.twig
  _sass/abstracts/_mixins.scss
  _sass/abstracts/_variables.scss
  _sass/components/_heading-group.scss
  _sass/components/_keyboard.scss
  _sass/components/_mouse.scss
  _sass/components/_page-split.scss
  _sass/components/_well.scss
  _sass/pages/_getting-started.scss
  _sass/styles.scss.twig
  _sass/utilities/_typography.scss
  _sass/utilities/_visibility.scss
  _sources/photoshoot/README.md
  _sources/photoshoot/colored-tanks-lineup.cfg
  _sources/photoshoot/ctf-scene.bzw
  _sources/photoshoot/ctf-scene.cfg
  _sources/photoshoot/ffa-tanks.cfg
  _sources/photoshoot/green_screen.conf
  _sources/photoshoot/offa-tanks.cfg
  _sources/photoshoot/rabbit-hunters.cfg
  _sources/photoshoot/rogue-tanks.cfg
  _sources/photoshoot/super-flags.bzw
  _sources/photoshoot/super-flags.cfg
  assets/images/documentation/user_interface_layout_small.jpg
  assets/images/getting-started/colored-tanks-lineup.png
  assets/images/getting-started/ctf-scene.png
  assets/images/getting-started/ffa-tanks.png
  assets/images/getting-started/jumbotron.jpg
  assets/images/getting-started/offa-tanks.png
  assets/images/getting-started/rabbit-hunters.png
  assets/images/getting-started/rogue-tanks.png
  assets/images/getting-started/super-flags.png
  assets/images/getting-started/user-interface-layout.jpg
Labels: enhancement, ready for merge
